<a href="https://colab.research.google.com/github/hyunil-cho/ml_practice/blob/main/GridSearchCv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.model_selection import GridSearchCV

In [ ]:
iris_data = load_iris()
X_train,x_test,y_train,y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state=121)

dtree = DecisionTreeClassifier()

prams = {
    "max_depth" : [1,2,3],
    "min_samples_split" : [2,3]
}


In [ ]:

grid_dtree = GridSearchCV(dtree,param_grid=prams,cv=3,refit=True)
grid_dtree.fit(X_train,y_train)

score_df = pd.DataFrame(grid_dtree.cv_results_)
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [ ]:
from math import e
from sklearn.preprocessing import LabelEncoder

items = ['냉장고', 'tv', '에어콘']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)


print(labels, encoder.classes_)

print(encoder.inverse_transform([1,1,1,1,1,1,0,0]))

# LabelEncoder의 경우, 선형회귀에서는 사용 X


[1 0 2] ['tv' '냉장고' '에어콘']
['냉장고' '냉장고' '냉장고' '냉장고' '냉장고' '냉장고' 'tv' 'tv']


#One-hot encoding

In [47]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['냉장고', 'tv', '에어콘']
items = np.array(items).reshape(-1,1)

encoder = OneHotEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.toarray()

items_pd = pd.DataFrame(items)
one_hot = pd.get_dummies(items_pd).astype(int)

print(labels)
print()
print(one_hot)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

   0_tv  0_냉장고  0_에어콘
0     0      1      0
1     1      0      0
2     0      0      1


#피처 스케일링 & 정규화

## 피처스케일링이란?
---
서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업을 의미

## 표준화
---
평균이 0, 분산이 1인 가우시안 정규 분포를 가진 값으로 변환 작업

## 정규화
---
서로 다른 피처의 크기를 통일하기 위해 크기를 변환하는 작업.
개별 데이터의 크기를 모두 똑같은 단위로 변경하는 작업

## 주의
---
피처 스케일링 진행 시, 학습 데이터로 scaler를 학습했다면, 동일한 scaler로 테스트 데이터에 적용해야 하며, 각각에 대하여 fit을 통해 학습시켜선 안된다.

In [59]:
  from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)

iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64